version: '3.9'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:1.18.0"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  booklog-app:
    container_name: booklog-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ACCESS_KEY=${ACCESS_KEY}
        - SECRET_KEY=${SECRET_KEY}
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/workspaces/booklog
      - node-module-volume:/workspaces/booklog/node_modules
    depends_on:
      - dynamodb-local
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
volumes:
  node-module-volume: